/**
 * SEO Keywords Manager - 100+ Keywords
 * Feature: birthday-card-sharing
 * Requirements: 5.1, 5.2, 5.3
 */

// Core website keywords (Arabic) - 50+ keywords
export const CORE_KEYWORDS_AR = [
  // أساسيات حساب العمر
  'ميلادك',
  'حاسبة العمر',
  'حساب العمر',
  'كم عمري',
  'تاريخ الميلاد',
  'عيد الميلاد',
  'حساب العمر بالهجري',
  'حساب العمر بالميلادي',
  'العمر بالأيام',
  'العمر بالساعات',
  'العمر بالدقائق',
  'العمر بالثواني',
  'حاسبة تاريخ الميلاد',
  'معرفة العمر',
  'حساب تاريخ الميلاد',
  // إضافات جديدة
  'احسب عمرك',
  'عمري كم',
  'كم عمرك',
  'حساب السن',
  'معرفة السن',
  'العمر الحقيقي',
  'العمر الدقيق',
  'حاسبة السن',
  'كم يوم عشت',
  'كم ساعة عشت',
  'إحصائيات الحياة',
  'رحلة الحياة',
  'أرقام الحظ',
  'حجر الميلاد',
  'زهرة الميلاد',
  'شخصية البرج',
  'صفات البرج',
  'توافق الأبراج',
  'تاريخ هجري',
  'عمر هجري',
  'تحويل التاريخ',
  'حاسبة التاريخ',
  'أيام العمر',
  'سنوات الحياة',
  'شهور العمر',
  'ساعات الحياة',
  'دقائق العمر',
  'ثواني الحياة',
  'البرج الفلكي',
  'الأبراج',
  'البرج الصيني',
  'حساب الأيام',
  'الفرق بين التواريخ',
  'عمر دقيق',
  'بطاقة عيد الميلاد',
  'بطاقة العمر',
  'مشاركة العمر',
  'تحميل بطاقة العمر',
];

// Core website keywords (English) - 50+ keywords
export const CORE_KEYWORDS_EN = [
  // Basic age calculation
  'miladak',
  'age calculator',
  'birthday calculator',
  'how old am i',
  'date of birth calculator',
  'age in days',
  'age in hours',
  'age in seconds',
  // New additions
  'calculate age',
  'age in minutes',
  'exact age',
  'age counter',
  'life statistics',
  'zodiac sign',
  'Chinese zodiac',
  'horoscope',
  'birth date',
  'age difference',
  'days lived',
  'life journey',
  'birthday countdown',
  'next birthday',
  'precise age',
  'birth calculator',
  'age finder',
  'date calculator',
  'time calculator',
  'life calculator',
  'birthday reminder',
  'age tracker',
  'birth year',
  'age verification',
  'chronological age',
  'biological age',
  'age estimation',
  'age computation',
  'date difference',
  'time difference',
  'calendar age',
  'anniversary calculator',
  'milestone calculator',
  'age milestones',
  'life milestones',
  'birthday card',
  'age card',
  'share age',
  'print age',
  'download age card',
  'social media sharing',
  'WhatsApp share',
  'birthday wishes',
  'age celebration',
  'life celebration',
  'personal statistics',
  'life stats',
  'age facts',
  'birthday facts',
  'age analysis',
  'life analysis',
  'age information',
  'birthday information',
  'age calculator online',
  'free age calculator',
  'accurate age calculator',
  'precise age calculator',
  'detailed age calculator',
];

// Page-specific keywords
export const PAGE_KEYWORDS = {
  home: [
    'حاسبة العمر الدقيقة',
    'احسب عمرك',
    'كم عمرك',
    'حساب العمر اون لاين',
    'حاسبة العمر مجانية',
    'معرفة العمر الحقيقي',
    'حساب العمر بدقة',
  ],
  chineseZodiac: [
    'البرج الصيني',
    'الأبراج الصينية',
    'حاسبة البرج الصيني',
    'برج الفأر',
    'برج الثور',
    'برج النمر',
    'برج الأرنب',
    'برج التنين',
    'برج الأفعى',
    'برج الحصان',
    'برج الماعز',
    'برج القرد',
    'برج الديك',
    'برج الكلب',
    'برج الخنزير',
    'التقويم الصيني',
    'السنة الصينية',
  ],
  historicalEvents: [
    'أحداث تاريخية',
    'هذا اليوم في التاريخ',
    'ماذا حدث في يوم ميلادي',
    'أحداث يوم الميلاد',
    'تاريخ اليوم',
    'أحداث مهمة',
    'تاريخ العالم',
  ],
  celebrities: [
    'مشاهير يوم الميلاد',
    'من ولد في يومي',
    'مشاهير ولدوا اليوم',
    'أعياد ميلاد المشاهير',
    'مشاهير عرب',
    'مشاهير عالميين',
  ],
  birthstones: [
    'حجر الميلاد',
    'زهرة الميلاد',
    'أحجار كريمة',
    'لون محظوظ',
    'حجر يناير',
    'حجر فبراير',
    'حجر مارس',
    'حجر أبريل',
    'حجر مايو',
    'حجر يونيو',
    'حجر يوليو',
    'حجر أغسطس',
    'حجر سبتمبر',
    'حجر أكتوبر',
    'حجر نوفمبر',
    'حجر ديسمبر',
    'زهور الشهور',
  ],
  tools: [
    'أدوات حساب العمر',
    'حاسبة الأيام',
    'حاسبة الفرق بين تاريخين',
    'حاسبة يوم الميلاد',
    'حاسبة العد التنازلي',
    'حاسبة السعرات',
    'حاسبة BMI',
    'حاسبة الحمل',
  ],
  articles: [
    'مقالات عن العمر',
    'نصائح صحية',
    'معلومات عن الأبراج',
    'حقائق عن تاريخ الميلاد',
  ],
};

// Long-tail keywords
export const LONG_TAIL_KEYWORDS = [
  'كيف احسب عمري بالضبط',
  'حساب العمر من تاريخ الميلاد',
  'معرفة عمري الحقيقي بالسنوات والشهور والأيام',
  'حاسبة العمر بالتاريخ الهجري والميلادي',
  'كم يوم عشت في حياتك',
  'كم ساعة عشت',
  'متى عيد ميلادي القادم',
  'كم باقي على عيد ميلادي',
  'ما هو برجي الصيني',
  'ماذا حدث يوم ولادتي',
  'من المشاهير ولد في نفس يومي',
  'ما هو حجر ميلادي',
  'ما هي زهرة ميلادي',
  'حساب العمر للأطفال',
  'حساب عمر الحمل',
];

export type PageType = keyof typeof PAGE_KEYWORDS;
